#!/bin/sh

### BEGIN INIT INFO
# Provides:		PLCmanager
# Required-Start:	$network $remote_fs $syslog
# Required-Stop:	$network $remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	PLC Manager
# Description:		Provides PLC connectivity through PLC modem application in external host.
### END INIT INFO

set -e

DAEMON="/home/PLCManager"
NAME="PLCManager"
PATH="/sbin:/bin:/usr/sbin:/usr/bin"
LOGFILE="/var/log/PLCManager.log"
CHROOT="/var/run/PLCManager/empty"

test -x "${DAEMON}" || exit 0

. /lib/lsb/init-functions

if [ ! -e "${LOGFILE}" ]
then
	touch "${LOGFILE}"
	chmod 640 "${LOGFILE}"
	chown root:adm "${LOGFILE}"
fi

if [ ! -d "${CHROOT}" ]
then
	mkdir -p "${CHROOT}"
fi

case "${1}" in
	start)
		log_daemon_msg "Starting PLC manager" "${NAME}"

		start-stop-daemon --start --background -m --oknodo --pidfile /var/run/PLCManager/PLCManager.pid --exec ${DAEMON}
		
		n=0
		while [ ${n} -le 5 ]
		do 
			_PID="$(if [ -e /var/run/PLCManager/PLCManager.pid ]; then cat /var/run/PLCManager/PLCManager.pid; fi)"
			if ! ps -C PLCManager | grep -qs "${_PID}"
			then
				break
			fi
			sleep 1
			n=$(( $n + 1 ))
		done

		if ! ps -C PLCManager | grep -qs "${_PID}"
		then
			log_warning_msg "PLCManager failed - probably invalid config."
			exit 1
		fi

		log_end_msg 0
		;;

	stop)
		log_daemon_msg "Stopping PLC manager" "${NAME}"

		start-stop-daemon --stop --pidfile /var/run/PLCManager/PLCManager.pid --oknodo --exec ${DAEMON}
		rm -f /var/run/PLCManager/PLCManager.pid

		log_end_msg 0
		;;

	restart)
		${0} stop
		${0} start
		;;

	reload|force-reload)
		log_daemon_msg "Reloading PLC manager configuration"

		start-stop-daemon --stop --pidfile /var/run/PLCManager/PLCManager.pid --signal 1 --exec $DAEMON

		log_end_msg "${?}"
		;;

	status)
		status_of_proc "${DAEMON}" "PLC manager"
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|reload|status}"
		exit 1
		;;
esac

exit 0
