#!/bin/sh

### BEGIN INIT INFO
# Provides:		PLCPppUp
# Required-Start:	$network $remote_fs $syslog
# Required-Stop:	$network $remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	PPP protocol Up
# Description:		Launch PPP to connect with SAMS70 app.
### END INIT INFO

#!/bin/sh
#/etc/init.d/PLCpppUp

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec pppd call g3 /dev/ttyUSB0 921600
  ;;
stop)
  exec killall pppd
  ;;
*)
  echo "Usage: /etc/init.d/nodeup {start|stop}"
  exit 1
  ;;
esac

exit 0