#!/bin/sh

### BEGIN INIT INFO
# Provides:		PLCWebServer
# Required-Start:	$PLCmanager $network $remote_fs $syslog
# Required-Stop:	$PLCmanager $network $remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	PLC Web Server
# Description:		Provides PLC Web Server to show PLC network information.
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/lib/nodejs:/usr/local/lib/node_modules

case "$1" in
  start)
	echo -n "Starting PLC Web Server..."
	cd /home/DCWebsockets/
	node app.js &
	sleep 1
	echo "Done."
	;;
  stop)
	echo -n "Stopping PLC Web Server... "
	killall node
	echo "Done."
	;;
  restart|force-reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit $?
